# Generated by Django 5.0.1 on 2024-01-07 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_author_post_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
